# Generated by Django 4.1.7 on 2023-04-21 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mynotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 21, 15, 38, 29, 886929))),
                ('title', models.CharField(max_length=100)),
                ('cate', models.CharField(max_length=100)),
                ('myfile', models.FileField(upload_to='Uploaded_Files')),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user_signup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 21, 15, 38, 29, 886929)),
        ),
    ]
