# Generated by Django 4.1.6 on 2023-04-23 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_feedback_alter_mynotes_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 23, 15, 33, 8, 556904)),
        ),
        migrations.AlterField(
            model_name='mynotes',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 23, 15, 33, 8, 556904)),
        ),
        migrations.AlterField(
            model_name='user_signup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 23, 15, 33, 8, 556904)),
        ),
    ]
